#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#
[ "$(uname -s)" = "Darwin" ] && BROWSER='open'

#
# Editors
#

[ "$(uname -s)" = "Darwin" ] && HOMEBREW_EDITOR='atom -n'
EDITOR='vim'
VISUAL='vim'
PAGER='less'

#
# Language
#

[ -z "$LANG" ] && LANG='en_US.UTF-8'

# Set go path, if dir exists.
[ -d ${HOME}/go ] && GOPATH=${HOME}/go

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  ./bin
  ~/bin
  ~/go/bin
  /usr/local/{bin,sbin}
  /{bin,sbin}
  /usr/{bin,sbin}
  ~/github/enterprise2
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
LESS='-F -g -i -M -R -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

# Ack
ACK_PAGER=less

#
# Temporary Files
#
TMPPREFIX="$(mktemp -d)/zsh"

# Set Ruby options.  Initially only disable warnings
RUBYOPT="-W0"

# Conveniently locate cloud drive :-P
ICLOUD_DRIVE="$HOME/Library/Mobile Documents/com~apple~CloudDocs"

# Always clean up when upgrading Homebrew packages
HOMEBREW_UPGRADE_CLEANUP=1

# Export everything in one go
export BROWSER HOMEBREW_EDITOR EDITOR VISUAL PAGER LANG GOPATH LESS LESSOPEN ACK_PAGER RUBYOPT TMPDIR ICLOUD_DRIVE HOMEBREW_UPGRADE_CLEANUP
