#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

#### ---:[ Aliases ]:--- ###
alias rm='nocorrect rm'
which exa > /dev/null && alias ls=exa
alias l='ls -lg'
alias ll='ls -lga'
alias ..='cd ..'
alias path='echo -e ${PATH//:/\\n}'
alias more="less"
which bat > /dev/null && { alias less=bat; alias cat=bat; export BAT_THEME="Monokai Extended" }
alias unzip="unzip -qq"
alias myprocs="ps aux | grep ${USER}"
alias nocmt="grep -v '^$\|^\s*\#'"
alias vag=vagrant
alias j="JEKYLL_ENV=local jekyll serve --watch --draft"
alias wtr='curl wttr.in/'
alias wtrr='curl wttr.in/Reading'
which ag > /dev/null && alias ag='ag --color --pager less' && alias ack=ag
alias atom='atom-beta'
which prettyping > /dev/null && alias ping="prettyping --nolegend"
which htop > /dev/null && alias top=htop

# Vagrant Aliases
alias v=vagrant
alias vst="vagrant status"
alias vstat=vst
alias vup="vagrant up"
alias vhalt="vagrant halt"
alias valt=vhalt
alias vupp="vagrant up --provision"
alias vssh="vagrant ssh"
# Use `vagrant ssh-config >> ~/.ssh/config` to add current config to ssh config
alias vsftp="sftp default"

# Lazy Git aliases
which hub > /dev/null && alias git=hub
alias gcom="git checkout master"
alias gup="git up"  # Uses the `up` alias in my .gitconfigcd
alias gst="git status"
alias g='git'
alias gb='git branch'
alias gbc='git checkout -b'
alias gc='git commit --verbose'
alias gco='git checkout'
alias gls='git log --topo-order --stat --pretty=format:"${_git_log_medium_format}"'
alias gld='git log --topo-order --stat --patch --full-diff --pretty=format:"${_git_log_medium_format}"'
alias gp='git push'


# Pull in AWS autocomplete manually as it doesn't work automatically - https://github.com/sorin-ionescu/prezto/issues/1142
which aws > /dev/null && {
  [ -f /usr/local/bin/aws_zsh_completer.sh ] && source /usr/local/bin/aws_zsh_completer.sh
}

# Pull in the Azure autocomplete. Cache it as it can be slow at times
which azure > /dev/null && {
  cache="${ZDOTDIR:-$HOME}/.zprezto/modules/completion/azure-cache.zsh"
  [ ! -f $cache ] && azure --completion > $cache
  source $cache
}

# Load rbenv automatically
which rbenv > /dev/null && eval "$(rbenv init -)"

# Load nodenv automatically
which nodenv > /dev/null && eval "$(nodenv init -)"

# added by travis gem
[ -f $HOME/.travis/travis.sh ] && source $HOME/.travis/travis.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
