#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

#### ---:[ Aliases ]:--- ###
alias rm='nocorrect rm'
alias l='ls -lh'
alias ll='ls -lha'
alias ..='cd ..'
alias entssh='ssh -i ~/Box\ Sync/Enterprise/Keys/id_ghenterprise -l admin'
alias path='echo -e ${PATH//:/\\n}'
alias more="less"
alias unzip="unzip -qq"
alias myprocs="ps aux | grep ${USER}"
alias nocmt="grep -v '^$\|^\s*\#'"
alias vag=vagrant
alias j="JEKYLL_ENV=local jekyll serve --watch --draft"
alias ghkey='cat "/Users/lildude/Box Sync/Enterprise/Keys/id_ghenterprise.pub" | pbcopy'
alias ghe-dev-key='echo $(ssh-keygen -y -f  ~/github/enterprise2/id_test) " fake-ssh DEADBEEF" | pbcopy'
alias wtr='curl wttr.in/'
alias wtrr='curl wttr.in/Reading'

# Vagrant Aliases
alias v=vagrant
alias vst="vagrant status"
alias vstat=vst
alias vup="vagrant up"
alias vhalt="vagrant halt"
alias valt=vhalt
alias vupp="vagrant up --provision"
alias vssh="vagrant ssh"
# Use `vagrant ssh-config >> ~/.ssh/config` to add current config to ssh config
alias vsftp="sftp default"

# Lazy Git aliases
which hub > /dev/null && alias git=hub
alias gcom="git checkout master"
alias gup="git up"  # Uses the `up` alias in my .gitconfigcd
alias gst="git status"

zstyle ':completion:*:*:git:*' script ~/bin/git-completion.sh

# Load rbenv automatically
which rbenv > /dev/null && eval "$(rbenv init -)"

# Start gpg-agent when we sign in, but only on OS X (for the moment)
# kill -0 checks to see if the pid exists
# TODO: This will need updating for Linux and also OS X when gpgtools is updated
# to include the latest gpg-agent which no longer takes the `--write-env-file` opt.
# I can probably switch to using the zprezto module at this point.
if [[ "$OSTYPE" == darwin* ]]; then
  if test -f $HOME/.gnupg/gpg-agent-info && kill -0 $(cut -d: -f 2 $HOME/.gnupg/gpg-agent-info) 2>/dev/null; then
      GPG_AGENT_INFO=$(cat $HOME/.gnupg/gpg-agent-info | cut -c 16-)
  else
  # No, gpg-agent not available; start gpg-agent
      eval $(gpg-agent --daemon --no-grab --write-env-file $HOME/.gnupg/gpg-agent-info)
  fi

  export GPG_AGENT_INFO
  export GPG_TTY=$(tty)
fi

# added by travis gem
[ -f /Users/lildude/.travis/travis.sh ] && source /Users/lildude/.travis/travis.sh
